import scipy as sp
import scipy.io
import numpy as np


def ccati_file(path, file, variable, ndata = True):
    """"
    Reads the .sav IDL file generated by CCATi and save the z-median to a variable in the .npy format.
    
    Parameters:
        path: string
            The path to the folder where the file is located.
            
        file: string
            The file's name.
            
        variable: string
            The variable's name to be used.
            
        ndata: bool, optional
            If True, there will be a file to store the number of samples per bin. Default is True.
            
    Returns:
        None
    """
    data = sp.io.readsav(path + file)
    median = np.nanmedian(data['zbins'], axis = 0)
    np.save(variable, median)

    if ndata == True:
        samples = data['zcbins']
        np.save(variable + '_N', samples)