import scipy as sp
import scipy.io
import numpy as np


def ccati_file(path, file, variable, ndata = None):
    """"
    Reads the .sav IDL file generated by CCATi and save the z-median to a variable in the .npy format.
    
    Parameters:
        path: string
            The path to the folder where the file is located.
            
        file: string
            The file's name.
            
        variable: string
            The variable's name to be used.
            
        ndata: string, Optional
            The name of the variable which will store the number of samples per bin. Default is None.
            
    Returns:
        None
    """
    data = sp.io.readsav(path + file)
    median = np.nanmedian(data['zbins'], axis = 0)
    np.save(variable, median)

    if ndata is not None:
        samples = data['zcbins']
        np.save(ndata, samples)
